### ISSUE TITLE
failed during catkin build 

### ISSUE THREAD

**Issue by aimanalimie** [dchavezromero/project_ws#1]
> The error is "gcc: error: libpython3.9.a: No such file or directory" 

 
![Screenshot from 2022-12-23 09-08-31](https://user-images.githubusercontent.com/102818861/209349229-1aa662e2-4357-488d-adfc-85419dba1355.png)
![Screenshot from 2022-12-23 09-09-02](https://user-images.githubusercontent.com/102818861/209349235-58eae43f-2952-427e-9026-555882597605.png)

Did you know why this happened?

Thank you

**Comment by dchavezromero** [comment]
This is an error specific to the version of python on your machine. This person seems to have solved a similar issue for python 3.7 doing [this](https://github.com/AprilRobotics/apriltag/issues/107#issuecomment-1221195040).

**Comment by aimanalimie** [comment]
I have tried to reinstall the your repository and did your suggestion, but the result remain the same

**Comment by dchavezromero** [comment]
I'm sorry to hear that. Regardless, this is an issue that is specific to your system, and is not exclusive to this project, so I'll have to close the issue.
Just googling the error code gives me numerous troubleshooting steps I can follow, I would advise that you spend some time trying those out. Alternatively ChatGPT could also be of use!
